# Generated by Django 5.1.4 on 2025-01-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentdb',
            name='Description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
