# Generated by Django 5.1.4 on 2025-01-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestappointmwntdb',
            name='Date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
