# Generated by Django 5.1.4 on 2025-01-09 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_guestappointmwntdb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestappointmwntdb',
            name='Fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
